# Generated by Django 2.2.4 on 2019-09-18 16:37

import Activity_Tracking_Web_App.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(blank=True, null=True, upload_to=Activity_Tracking_Web_App.models.test_content_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to=Activity_Tracking_Web_App.models.content_file_name)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Activity_Tracking_Web_App.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id'